"""
AI Tutor — Core Engine Data Models.

Internal data structures used by the deterministic engines
(Math Checker, Student Model, Curriculum Model).
"""

from typing import Optional
from pydantic import BaseModel, Field


class AnswerResult(BaseModel):
    """The result of evaluating a student's answer.

    Produced by the Math Checker and consumed by the Student Model
    and Tutor Controller to decide the next action.
    """

    is_correct: bool = Field(..., description="True if the answer is mathematically fully correct")
    is_partial: bool = Field(default=False, description="True if the answer is partially correct (e.g., 1 of 2 roots)")
    error_type: Optional[str] = Field(default=None, description="Categorized error (e.g., 'sign_error', 'parse_error', 'incomplete_solution')")
    misconception_id: Optional[str] = Field(default=None, description="Mapped misconception ID if a known error pattern is detected")
    feedback_hint: Optional[str] = Field(default=None, description="Specific feedback generated by the checker (not the LLM) based on the exact error")

    @property
    def is_wrong(self) -> bool:
        return not self.is_correct and not self.is_partial
